language: java
sudo: false
jdk:
- oraclejdk7
install: true
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_8f5382672e20_key -iv $encrypted_8f5382672e20_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a79db88177c15928246a
    on_success: change
    on_failure: always
    on_start: never
